// Crimson Escape — game-internal strings, all four languages. Per the
// i18n.ts contract, game-internal lines stay in their own table; only the
// card/shell/win chrome lives in src/i18n.ts.
import { Lang } from '../../lang';
import { HintKey, ItemId, MsgKey } from './logic';

type Table<K extends string> = Record<Lang, Record<K, string>>;

export const MSG: Table<MsgKey> = {
  en: {
    intro: 'You wake on a hard bed. The room is crimson. The door is locked.',
    lookPillow: 'Something hard under the pillow — a small brass key!',
    pillowEmpty: 'Just a worn pillow.',
    underBedDark: 'It is pitch black under the bed.',
    underBedLit: 'The beam catches something — a power cord!',
    underBedEmpty: 'Only dust left under there.',
    curtainsOpened: 'You drag the heavy curtains open. Dusty light floods in.',
    curtainsAlready: 'Dusty light pours through the window.',
    sillBlocked: 'Heavy curtains cover the window.',
    sillBattery: 'A single battery sits on the windowsill.',
    sillEmpty: 'Nothing else on the sill.',
    calendarDim: 'A calendar, but it is too dim to read.',
    calendarRead: 'An old calendar, frozen on one year: 2004.',
    topDrawerLocked: 'Locked. A tiny brass keyhole.',
    topDrawerUnlock: 'The brass key turns. Inside: a USB stick and a crumpled note.',
    topDrawerEmpty: 'The drawer is empty now. The key stays in the lock.',
    bottomDrawerFind: 'An old flashlight rolls around inside. Dead.',
    bottomDrawerEmpty: 'Nothing else in the bottom drawer.',
    projectorNoPower: 'An old projector. Its power cord is missing.',
    projectorPlug: 'You connect the cord. A red standby light blinks on.',
    projectorNoUsb: 'Powered up, but nothing to play. There is a USB port.',
    projectorUsb: 'The USB stick clicks into the port.',
    projectorPlay: 'The projector whirs to life…',
    clipDone: 'The dancing figure stops — and points at the painting.',
    projectorAgain: 'The projector hums. The figure still points at the painting.',
    paintingStuck: 'A gloomy painting, bolted tight to the wall.',
    paintingSlid: 'The painting slides aside — a steel safe!',
    safeEmpty: 'The safe hangs open, empty.',
    codeWrong: 'The keypad blinks red.',
    codeRight: 'Clunk. The safe swings open — a golden key!',
    doorLocked: 'The door is locked. Of course it is.',
    doorOpened: 'The key turns. The door creaks open — you are free!',
    combineLit: 'The flashlight flickers on!',
  },
  ja: {
    intro: '固いベッドで目が覚めた。部屋は真紅。ドアには鍵がかかっている。',
    lookPillow: '枕の下に何か固いもの——小さな真鍮の鍵だ!',
    pillowEmpty: 'くたびれた枕だけ。',
    underBedDark: 'ベッドの下は真っ暗だ。',
    underBedLit: '光の先に何かある——電源コードだ!',
    underBedEmpty: 'もうほこりしか残っていない。',
    curtainsOpened: '重いカーテンを開けた。ほこりっぽい光が差し込む。',
    curtainsAlready: '窓から光が差し込んでいる。',
    sillBlocked: '重いカーテンが窓をおおっている。',
    sillBattery: '窓辺に電池がひとつ置いてある。',
    sillEmpty: '窓辺にはもう何もない。',
    calendarDim: 'カレンダーがあるが、暗くて読めない。',
    calendarRead: '古いカレンダー。ある年で止まっている——2004。',
    topDrawerLocked: '鍵がかかっている。小さな真鍮の鍵穴。',
    topDrawerUnlock: '真鍮の鍵が回った。中にはUSBメモリと、しわくちゃのメモ。',
    topDrawerEmpty: '引き出しは空だ。鍵は差したまま。',
    bottomDrawerFind: '古い懐中電灯が転がっている。電池切れだ。',
    bottomDrawerEmpty: '下の引き出しには何もない。',
    projectorNoPower: '古い映写機。電源コードがない。',
    projectorPlug: 'コードをつないだ。赤いランプが点滅する。',
    projectorNoUsb: '電源は入ったが、何も再生できない。USBポートがある。',
    projectorUsb: 'USBメモリがカチッとはまった。',
    projectorPlay: '映写機がうなりを上げて動き出す…',
    clipDone: '踊る影が止まり——絵を指さした。',
    projectorAgain: '映写機がうなっている。影はまだ絵を指している。',
    paintingStuck: '暗い絵。壁にしっかり固定されている。',
    paintingSlid: '絵が横にすべった——鋼鉄の金庫だ!',
    safeEmpty: '金庫は開いたまま、空っぽだ。',
    codeWrong: 'キーパッドが赤く点滅した。',
    codeRight: 'ガチャン。金庫が開いた——金色の鍵だ!',
    doorLocked: 'ドアには鍵がかかっている。やっぱり。',
    doorOpened: '鍵が回った。ドアがきしみながら開く——脱出だ!',
    combineLit: '懐中電灯がついた!',
  },
  cmn: {
    intro: '你在硬床上醒来。房间一片深红。门锁着。',
    lookPillow: '枕头下有硬东西——一把小铜钥匙!',
    pillowEmpty: '只是个旧枕头。',
    underBedDark: '床底下漆黑一片。',
    underBedLit: '光束照到了什么——一根电源线!',
    underBedEmpty: '床下只剩灰尘了。',
    curtainsOpened: '你拉开厚重的窗帘。灰蒙蒙的光照了进来。',
    curtainsAlready: '光线从窗户照进来。',
    sillBlocked: '厚窗帘挡住了窗户。',
    sillBattery: '窗台上放着一节电池。',
    sillEmpty: '窗台上没有别的了。',
    calendarDim: '有本日历,太暗了看不清。',
    calendarRead: '旧日历,停在同一年:2004。',
    topDrawerLocked: '锁着的。有个小小的铜锁孔。',
    topDrawerUnlock: '铜钥匙转动了。里面有一个U盘和一张皱纸条。',
    topDrawerEmpty: '抽屉空了。钥匙留在锁上。',
    bottomDrawerFind: '里面滚着一支旧手电筒。没电了。',
    bottomDrawerEmpty: '下层抽屉没有别的了。',
    projectorNoPower: '一台旧放映机。电源线不见了。',
    projectorPlug: '你接上了电源线。红色待机灯闪了起来。',
    projectorNoUsb: '通电了,但没有东西可放。有个USB接口。',
    projectorUsb: 'U盘咔哒一声插好了。',
    projectorPlay: '放映机嗡嗡地转了起来…',
    clipDone: '跳舞的身影停下——指向了那幅画。',
    projectorAgain: '放映机还在嗡嗡响。身影仍指着那幅画。',
    paintingStuck: '一幅阴沉的画,牢牢固定在墙上。',
    paintingSlid: '画滑开了——一个钢制保险箱!',
    safeEmpty: '保险箱开着,空空如也。',
    codeWrong: '键盘闪了红灯。',
    codeRight: '咔嚓。保险箱开了——一把金钥匙!',
    doorLocked: '门锁着。果然。',
    doorOpened: '钥匙转动了。门吱呀打开——你自由了!',
    combineLit: '手电筒亮了!',
  },
  yue: {
    intro: '你喺張硬床度醒返。成間房都係深紅色。道門鎖咗。',
    lookPillow: '枕頭底下有嚿硬嘢——一條細細嘅銅鎖匙!',
    pillowEmpty: '得個舊枕頭。',
    underBedDark: '床下底黑漆漆。',
    underBedLit: '電筒照到啲嘢——一條電源線!',
    underBedEmpty: '床下底淨返啲塵。',
    curtainsOpened: '你拉開幅厚窗簾。灰濛濛嘅光照咗入嚟。',
    curtainsAlready: '啲光由個窗照入嚟。',
    sillBlocked: '厚窗簾遮住咗個窗。',
    sillEmpty: '窗台冇其他嘢喇。',
    sillBattery: '窗台上面有一粒電池。',
    calendarDim: '有本日曆,太暗睇唔到。',
    calendarRead: '本舊日曆,停咗喺同一年:2004。',
    topDrawerLocked: '鎖咗。有個細細嘅銅鎖窿。',
    topDrawerUnlock: '銅鎖匙轉得郁。入面有隻USB手指同一張皺晒嘅字條。',
    topDrawerEmpty: '個櫃桶空晒喇。條鎖匙留返喺個鎖度。',
    bottomDrawerFind: '入面碌住支舊電筒。冇電嘅。',
    bottomDrawerEmpty: '下層櫃桶冇其他嘢喇。',
    projectorNoPower: '一部舊放映機。條電源線唔見咗。',
    projectorPlug: '你駁好條線。粒紅色待機燈閃下閃下。',
    projectorNoUsb: '有電喇,但係冇嘢可以播。有個USB插口。',
    projectorUsb: '隻USB手指咔一聲插好咗。',
    projectorPlay: '部放映機嗡嗡聲轉起上嚟…',
    clipDone: '跳舞嗰個人影停低——指住幅畫。',
    projectorAgain: '部放映機仲嗡嗡聲。個人影仲係指住幅畫。',
    paintingStuck: '一幅灰暗嘅畫,實一實咁釘喺牆度。',
    paintingSlid: '幅畫滑開咗——一個鋼保險箱!',
    safeEmpty: '保險箱開住,空嘅。',
    codeWrong: '個鍵盤閃紅燈。',
    codeRight: '咔嚓。保險箱打開咗——一條金鎖匙!',
    doorLocked: '道門鎖咗。梗係啦。',
    doorOpened: '鎖匙轉得郁。道門咿呀一聲打開——你自由喇!',
    combineLit: '支電筒著咗!',
  },
};

export const HINT: Table<HintKey> = {
  en: {
    'hint.pillow': 'That pillow looks a little lumpy.',
    'hint.bottomDrawer': 'The dresser has a drawer that is not locked.',
    'hint.curtains': 'It is awfully dark in here. Maybe let some light in?',
    'hint.sill': 'Now that it is bright, check around the window.',
    'hint.combine': 'A dead flashlight and a battery… they belong together.',
    'hint.underBed': 'It is dark under the bed. Shine a light and look again.',
    'hint.topDrawer': 'A brass key should fit a brass keyhole.',
    'hint.plug': 'The projector is dead without its power cord.',
    'hint.usb': 'The projector is powered. What could it play?',
    'hint.play': 'Everything is connected. Switch the projector on.',
    'hint.painting': 'The figure pointed straight at that painting.',
    'hint.code': 'The note mentions a year. Is a year written anywhere?',
    'hint.door': 'A golden key… and one locked door.',
    'hint.won': 'You already escaped!',
  },
  ja: {
    'hint.pillow': 'あの枕、少しふくらんでいない?',
    'hint.bottomDrawer': 'たんすには鍵のかかっていない引き出しがある。',
    'hint.curtains': 'ずいぶん暗い。光を入れてみたら?',
    'hint.sill': '明るくなった。窓のまわりを調べてみよう。',
    'hint.combine': '電池切れの懐中電灯と電池…組み合わせてみたら?',
    'hint.underBed': 'ベッドの下は暗い。明かりで照らしてもう一度。',
    'hint.topDrawer': '真鍮の鍵は真鍮の鍵穴に合うはず。',
    'hint.plug': '映写機はコードがないと動かない。',
    'hint.usb': '電源は入った。何を再生できる?',
    'hint.play': '全部つながった。映写機をつけよう。',
    'hint.painting': '影はまっすぐあの絵を指していた。',
    'hint.code': 'メモには「年」とある。どこかに年が書いていない?',
    'hint.door': '金色の鍵…そして鍵のかかったドア。',
    'hint.won': 'もう脱出したよ!',
  },
  cmn: {
    'hint.pillow': '那个枕头看起来有点鼓。',
    'hint.bottomDrawer': '柜子有个没上锁的抽屉。',
    'hint.curtains': '这里太暗了。让点光进来吧?',
    'hint.sill': '亮了。去窗户附近找找。',
    'hint.combine': '没电的手电筒和一节电池…它们是一对。',
    'hint.underBed': '床下很黑。用灯照着再看一次。',
    'hint.topDrawer': '铜钥匙应该配铜锁孔。',
    'hint.plug': '放映机没有电源线开不了。',
    'hint.usb': '放映机通电了。能放什么呢?',
    'hint.play': '都接好了。打开放映机吧。',
    'hint.painting': '身影直直指向那幅画。',
    'hint.code': '纸条提到一个年份。哪里写着年份呢?',
    'hint.door': '一把金钥匙…和一扇锁着的门。',
    'hint.won': '你已经逃出去啦!',
  },
  yue: {
    'hint.pillow': '個枕頭好似有啲脹。',
    'hint.bottomDrawer': '個櫃有個冇鎖嘅櫃桶。',
    'hint.curtains': '呢度好黑。不如放啲光入嚟?',
    'hint.sill': '光猛咗喇。去個窗附近搵下。',
    'hint.combine': '冇電嘅電筒同一粒電池…佢哋係一對。',
    'hint.underBed': '床下底好黑。攞盞燈照住再睇多次。',
    'hint.topDrawer': '銅鎖匙應該啱銅鎖窿。',
    'hint.plug': '部放映機冇電源線開唔到。',
    'hint.usb': '放映機有電喇。可以播啲乜呢?',
    'hint.play': '全部駁好晒。開部放映機啦。',
    'hint.painting': '個人影直情指住嗰幅畫。',
    'hint.code': '張字條提到一個年份。邊度有寫年份呢?',
    'hint.door': '一條金鎖匙…同一道鎖住嘅門。',
    'hint.won': '你已經走甩咗喇!',
  },
};

// Tray captions: selecting an item "examines" it — the note carries the
// safe-code clue, so its caption IS the puzzle.
export const ITEM: Table<ItemId> = {
  en: {
    brassKey: 'A small brass key.',
    flashlight: 'A flashlight. Completely dead.',
    flashlightLit: 'The flashlight, shining bright.',
    battery: 'A chunky battery with some life left.',
    powerCord: 'A dusty power cord.',
    usbDrive: 'A USB stick labeled “DANCE”.',
    note: 'The note reads: “The code is the year this room was born.”',
    doorKey: 'A golden key. It looks important.',
  },
  ja: {
    brassKey: '小さな真鍮の鍵。',
    flashlight: '懐中電灯。完全に電池切れ。',
    flashlightLit: '明るく光る懐中電灯。',
    battery: 'まだ使えそうな大きな電池。',
    powerCord: 'ほこりまみれの電源コード。',
    usbDrive: '「DANCE」と書かれたUSBメモリ。',
    note: 'メモにはこうある。「暗証番号は、この部屋が生まれた年」',
    doorKey: '金色の鍵。大事なものみたいだ。',
  },
  cmn: {
    brassKey: '一把小铜钥匙。',
    flashlight: '一支手电筒。完全没电。',
    flashlightLit: '亮着的手电筒。',
    battery: '一节还有电的大电池。',
    powerCord: '一根落满灰的电源线。',
    usbDrive: '写着“DANCE”的U盘。',
    note: '纸条上写着:“密码是这个房间诞生的那一年。”',
    doorKey: '一把金钥匙。看起来很重要。',
  },
  yue: {
    brassKey: '一條細銅鎖匙。',
    flashlight: '一支電筒。完全冇電。',
    flashlightLit: '著住嘅電筒。',
    battery: '一粒仲有電嘅大電池。',
    powerCord: '一條積晒塵嘅電源線。',
    usbDrive: '寫住「DANCE」嘅USB手指。',
    note: '張字條寫住:「密碼係呢間房出世嗰一年。」',
    doorKey: '一條金鎖匙。睇落好重要。',
  },
};

export const ITEM_EMOJI: Record<ItemId, string> = {
  brassKey: '🗝️',
  flashlight: '🔦',
  flashlightLit: '🔦',
  battery: '🔋',
  powerCord: '🔌',
  usbDrive: '💾',
  note: '📜',
  doorKey: '🔑',
};

export const WALL_NAME: Record<Lang, [string, string, string, string]> = {
  en: ['The bed', 'The window', 'The dresser', 'The door'],
  ja: ['ベッド', '窓', 'たんす', 'ドア'],
  cmn: ['床', '窗户', '柜子', '门'],
  yue: ['張床', '個窗', '個櫃', '道門'],
};
