// GENERATED by tools/gen_images_ts.mjs — do not edit by hand.
/* eslint-disable @typescript-eslint/no-require-imports */

export const SPOTIT_ICONS: Record<string, number> = {
  dog: require('../../assets/game/spotit/dog.png'),
  cat: require('../../assets/game/spotit/cat.png'),
  lion: require('../../assets/game/spotit/lion.png'),
  frog: require('../../assets/game/spotit/frog.png'),
  panda: require('../../assets/game/spotit/panda.png'),
  fox: require('../../assets/game/spotit/fox.png'),
  monkey: require('../../assets/game/spotit/monkey.png'),
  pig: require('../../assets/game/spotit/pig.png'),
  rabbit: require('../../assets/game/spotit/rabbit.png'),
  koala: require('../../assets/game/spotit/koala.png'),
  unicorn: require('../../assets/game/spotit/unicorn.png'),
  octopus: require('../../assets/game/spotit/octopus.png'),
  crab: require('../../assets/game/spotit/crab.png'),
  fish: require('../../assets/game/spotit/fish.png'),
  butterfly: require('../../assets/game/spotit/butterfly.png'),
  ladybug: require('../../assets/game/spotit/ladybug.png'),
  blossom: require('../../assets/game/spotit/blossom.png'),
  sunflower: require('../../assets/game/spotit/sunflower.png'),
  apple: require('../../assets/game/spotit/apple.png'),
  banana: require('../../assets/game/spotit/banana.png'),
  strawberry: require('../../assets/game/spotit/strawberry.png'),
  pizza: require('../../assets/game/spotit/pizza.png'),
  icecream: require('../../assets/game/spotit/icecream.png'),
  balloon: require('../../assets/game/spotit/balloon.png'),
  car: require('../../assets/game/spotit/car.png'),
  plane: require('../../assets/game/spotit/plane.png'),
  rocket: require('../../assets/game/spotit/rocket.png'),
  soccer: require('../../assets/game/spotit/soccer.png'),
  rainbow: require('../../assets/game/spotit/rainbow.png'),
  star: require('../../assets/game/spotit/star.png'),
  gift: require('../../assets/game/spotit/gift.png'),
};

// precomputed silhouettes (rn-web tintColor masks stretch/crop sprites)
export const SPOTIT_SHADOWS: Record<string, number> = {
  dog: require('../../assets/game/spotit/dog_shadow.png'),
  cat: require('../../assets/game/spotit/cat_shadow.png'),
  lion: require('../../assets/game/spotit/lion_shadow.png'),
  frog: require('../../assets/game/spotit/frog_shadow.png'),
  panda: require('../../assets/game/spotit/panda_shadow.png'),
  fox: require('../../assets/game/spotit/fox_shadow.png'),
  monkey: require('../../assets/game/spotit/monkey_shadow.png'),
  pig: require('../../assets/game/spotit/pig_shadow.png'),
  rabbit: require('../../assets/game/spotit/rabbit_shadow.png'),
  koala: require('../../assets/game/spotit/koala_shadow.png'),
  unicorn: require('../../assets/game/spotit/unicorn_shadow.png'),
  octopus: require('../../assets/game/spotit/octopus_shadow.png'),
  crab: require('../../assets/game/spotit/crab_shadow.png'),
  fish: require('../../assets/game/spotit/fish_shadow.png'),
  butterfly: require('../../assets/game/spotit/butterfly_shadow.png'),
  ladybug: require('../../assets/game/spotit/ladybug_shadow.png'),
  blossom: require('../../assets/game/spotit/blossom_shadow.png'),
  sunflower: require('../../assets/game/spotit/sunflower_shadow.png'),
  apple: require('../../assets/game/spotit/apple_shadow.png'),
  banana: require('../../assets/game/spotit/banana_shadow.png'),
  strawberry: require('../../assets/game/spotit/strawberry_shadow.png'),
  pizza: require('../../assets/game/spotit/pizza_shadow.png'),
  icecream: require('../../assets/game/spotit/icecream_shadow.png'),
  balloon: require('../../assets/game/spotit/balloon_shadow.png'),
  car: require('../../assets/game/spotit/car_shadow.png'),
  plane: require('../../assets/game/spotit/plane_shadow.png'),
  rocket: require('../../assets/game/spotit/rocket_shadow.png'),
  soccer: require('../../assets/game/spotit/soccer_shadow.png'),
  rainbow: require('../../assets/game/spotit/rainbow_shadow.png'),
  star: require('../../assets/game/spotit/star_shadow.png'),
  gift: require('../../assets/game/spotit/gift_shadow.png'),
};

export const SCENE_IMAGES: Record<string, number> = {
};

export const UI_IMAGES = {
  logo: require('../../assets/game/ui/logo.png'),
  menu_bg: require('../../assets/game/ui/menu_bg.jpg'),
} as const;
