// Emit src/assets/images.ts — Metro needs static require() calls, so this
// file is regenerated whenever the asset manifest changes.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const root = path.dirname(path.dirname(url.fileURLToPath(import.meta.url)));
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'src/assets/manifest.json'), 'utf8'));
const exists = (rel) => fs.existsSync(path.join(root, 'assets/game', rel));

const lines = [
  '// GENERATED by tools/gen_images_ts.mjs — do not edit by hand.',
  '/* eslint-disable @typescript-eslint/no-require-imports */',
  '',
  'export const SPOTIT_ICONS: Record<string, number> = {',
];
for (const name of manifest.spotit.icons) {
  lines.push(`  ${name}: require('../../assets/game/spotit/${name}.png'),`);
}
lines.push('};', '', '// precomputed silhouettes (rn-web tintColor masks stretch/crop sprites)');
lines.push('export const SPOTIT_SHADOWS: Record<string, number> = {');
for (const name of manifest.spotit.icons) {
  if (exists(`spotit/${name}_shadow.png`)) {
    lines.push(`  ${name}: require('../../assets/game/spotit/${name}_shadow.png'),`);
  }
}
lines.push('};', '', 'export const SCENE_IMAGES: Record<string, number> = {');
const sceneFiles = new Set();
for (const d of manifest.diff) {
  if (d.pool) {
    sceneFiles.add(d.image);
    for (const e of d.pool) sceneFiles.add(e.patch);
  } else {
    sceneFiles.add(d.imageA);
    sceneFiles.add(d.imageB);
  }
}
for (const h of manifest.hidden) {
  sceneFiles.add(h.image);
  for (const t of h.targets) {
    sceneFiles.add(t.thumb);
    const shadow = t.thumb.replace(/\.png$/, '_shadow.png');
    if (exists(shadow)) sceneFiles.add(shadow);
  }
}
for (const st of manifest.stories ?? []) {
  for (const n of Object.values(st.nodes)) {
    sceneFiles.add(n.image);
    if (n.scare) sceneFiles.add(n.scare.pop);
    for (const c of n.choices ?? []) if (c.icon) sceneFiles.add(c.icon);
  }
}
for (const r of manifest.escape ?? []) {
  sceneFiles.add(r.image);
  for (const h of r.hotspots) {
    if (h.pop) sceneFiles.add(h.pop);
    if (h.after?.patch) sceneFiles.add(h.after.patch);
  }
}
for (const f of [...sceneFiles].sort()) {
  lines.push(`  '${f}': require('../../assets/game/${f}'),`);
}
lines.push('};', '', '// small jpg derivatives for picker cards (fall back to full image)');
lines.push('export const SCENE_THUMBS: Record<string, number> = {');
const thumbable = new Set();
for (const d of manifest.diff) thumbable.add(d.image ?? d.imageA);
for (const h of manifest.hidden) thumbable.add(h.image);
for (const r of manifest.escape ?? []) thumbable.add(r.image);
for (const f of [...thumbable].sort()) {
  const t = f.replace(/\.(png|jpg)$/, '_thumb.jpg');
  if (exists(t)) lines.push(`  '${f}': require('../../assets/game/${t}'),`);
}
lines.push('};', '', 'export const DRESSUP_ICONS: Record<string, number> = {');
for (const name of manifest.dressup ?? []) {
  if (exists(`dressup/${name}.png`)) {
    lines.push(`  ${name}: require('../../assets/game/dressup/${name}.png'),`);
  }
}
lines.push('};', '', 'export const CHARACTER_ICONS: Record<string, number> = {');
for (const name of manifest.characters ?? []) {
  if (exists(`characters/${name}.png`)) {
    lines.push(`  ${name}: require('../../assets/game/characters/${name}.png'),`);
  }
}
lines.push('};', '', 'export const ANIMAL_ICONS: Record<string, number> = {');
for (const [animal, poses] of Object.entries(manifest.animalPoses ?? {})) {
  for (const pose of poses) {
    if (exists(`animals/${animal}_${pose}.png`)) {
      lines.push(`  ${animal}_${pose}: require('../../assets/game/animals/${animal}_${pose}.png'),`);
    }
  }
}
lines.push('};', '', 'export const RHYME_SPRITES: Record<string, number> = {');
for (const f of (fs.existsSync(path.join(root, 'assets/game/rhyme')) ? fs.readdirSync(path.join(root, 'assets/game/rhyme')).sort() : [])) {
  const key = f.replace(/\.(png|jpg)$/, '');
  lines.push(`  ${key}: require('../../assets/game/rhyme/${f}'),`);
}
lines.push('};', '', 'export const UI_IMAGES = {');
for (const f of fs.readdirSync(path.join(root, 'assets/game/ui')).sort()) {
  const key = f.replace(/\.(png|jpg)$/, '');
  lines.push(`  ${key}: require('../../assets/game/ui/${f}'),`);
}
lines.push('} as const;', '');

fs.writeFileSync(path.join(root, 'src/assets/images.ts'), lines.join('\n'));
console.log('wrote src/assets/images.ts');
