"""Pre-generate all narration with Gemini 2.5 Pro TTS (SoTA voice).

Collects every line the app speaks (story texts, choice labels, scare
reveals, rule/odd-one instructions, recall variants, UI prompts), renders
each once to public/voice/<sha1>.mp3, and writes src/assets/voice.ts
mapping exact text -> filename. say() plays the file when mapped and only
falls back to Web Speech for unmapped strings.

Usage: python3 tools/gen_voice.py   (skips existing clips)
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from google import genai  # noqa: E402
from google.genai import types  # noqa: E402

ROOT = Path(__file__).parent.parent
VOICE_DIR = ROOT / "public" / "voice"
MANIFEST = ROOT / "src" / "assets" / "manifest.json"
VOICE_TS = ROOT / "src" / "assets" / "voice.ts"

_client = None


def client() -> genai.Client:
    global _client
    if _client is None:
        _client = genai.Client(vertexai=True, project="adk-coding-agents", location="global")
    return _client


EMOJI = re.compile(r"[\U0001F000-\U0001FAFF☀-➿⬀-⯿]")


def spoken_form(text: str) -> str:
    return EMOJI.sub("", text).strip()


def collect_lines() -> list[str]:
    lines: set[str] = set()
    m = json.loads(MANIFEST.read_text())
    for st in m.get("stories", []):
        for n in st["nodes"].values():
            lines.add(n["text"])
            for c in n.get("choices", []):
                lines.add(c["label"])
            if "scare" in n:
                lines.add(n["scare"]["reveal"])
    # game instructions (kept in lockstep with iconCategories.ts)
    cat = (ROOT / "src" / "games" / "iconCategories.ts").read_text()
    lines.update(re.findall(r"tap: '([^']+)'", cat))
    lines.update(re.findall(r"not: '([^']+)'", cat))
    lines.add("Which one does not belong?")
    for n in range(1, 11):
        lines.add(f"Memory check! Do rule number {n} again. Do you remember it?")
    lines.add("How many players?")
    lines.add("Two player mode is on!")
    return sorted(lines)


def fname_for(text: str) -> str:
    return hashlib.sha1(spoken_form(text).encode()).hexdigest()[:16] + ".mp3"


def synth(text: str) -> bool:
    out = VOICE_DIR / fname_for(text)
    if out.exists():
        return True
    say = spoken_form(text)
    for attempt in range(3):
        try:
            resp = client().models.generate_content(
                model="gemini-2.5-pro-preview-tts",
                contents=say,
                config=types.GenerateContentConfig(
                    response_modalities=["AUDIO"],
                    speech_config=types.SpeechConfig(voice_config=types.VoiceConfig(
                        prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name="Leda")))),
            )
            data = resp.candidates[0].content.parts[0].inline_data.data
            with tempfile.NamedTemporaryFile(suffix=".raw", delete=False) as f:
                f.write(data)
                raw = f.name
            subprocess.run(["ffmpeg", "-y", "-v", "error", "-f", "s16le", "-ar", "24000",
                            "-ac", "1", "-i", raw, "-codec:a", "libmp3lame", "-q:a", "4",
                            str(out)], check=True)
            Path(raw).unlink()
            print(f"  voiced: {say[:60]!r}")
            return True
        except Exception as e:  # noqa: BLE001
            print(f"  retry {attempt + 1} {say[:40]!r}: {str(e)[:90]}")
    return False


def main() -> None:
    VOICE_DIR.mkdir(parents=True, exist_ok=True)
    lines = collect_lines()
    print(f"{len(lines)} lines to voice")
    with ThreadPoolExecutor(4) as ex:
        results = list(ex.map(synth, lines))
    ok = [t for t, r in zip(lines, results) if r]
    entries = ",\n".join(f"  {json.dumps(spoken_form(t))}: '{fname_for(t)}'" for t in sorted(ok))
    VOICE_TS.write_text(
        "// GENERATED by tools/gen_voice.py — exact spoken text -> pre-rendered clip.\n"
        "export const VOICE: Record<string, string> = {\n" + entries + ",\n};\n")
    print(f"voiced {len(ok)}/{len(lines)}; wrote src/assets/voice.ts")


if __name__ == "__main__":
    main()
